name: Auto Api

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: 0 */6 * * *
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: Test Api #Api调用
      run: |
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > time.log
        python 1.py
        
           
    - name: commit #上传新的refresh_token
      run: |
        git config --global user.email hillj5609@gmail.com
        git config --global user.name JohnHill5609
        git add .
        git commit -m "update new refresh_token" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
